```{r}
library(PMCMR)
options(scipen = 999) 
```

```{r}
# -----------------------
# GINI
# -----------------------

LR <- c(0.711,0.899,0.565,0.743,0.638,0.715,0.755,0.812,0.497)
DT <- c(0.704,0.906,0.366,0.680,0.706,0.665,0.678,0.713,0.506)
RF <- c(0.727,0.916,0.593,0.871,0.824,0.825,0.861,0.907,0.561)
XGB <- c(0.733,0.924,0.585,0.865,0.837,0.853,0.888,0.90,0.565)

df <- data.frame(LR, DT, RF, XGB)


sample <- matrix(c(df$LR, df$DT, df$RF, df$XGB), ncol=4)
colnames(sample) <- c("LR", "DT", "RF", "XGB")


boxplot(df$LR, df$DT, df$RF, df$XGB)

print(sample)
friedman.test(sample)
posthoc.friedman.nemenyi.test(sample)
```


```{r}
# -----------------------
# GINI
# -----------------------

LR <- c(0.366,0.962,0.573,0.481,0.253,0.31,0.434,0.6,0.508)
DT <- c(0.343,0.961,0.447,0.431,0.404,0.395,0.39,0.56,0.509)
RF <- c(0.387,0.968,0.627,0.659,0.63,0.614,0.653,0.769,0.556)
XGB <- c(0.399,0.97,0.637,0.705,0.655,0.673,0.756,0.754,0.559)
df <- data.frame(LR, DT, RF, XGB)


sample <- matrix(c(df$LR, df$DT, df$RF, df$XGB), ncol=4)
colnames(sample) <- c("LR", "DT", "RF", "XGB")


boxplot(df$LR, df$DT, df$RF, df$XGB)

print(sample)
friedman.test(sample)
posthoc.friedman.nemenyi.test(sample)
```
